name: backend_dart_kpis
description: Backend Dart + Supabase + Socket.IO (KPIs tiempo real)
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  socket_io: ^1.0.1
  supabase: ^2.3.5
  dotenv: ^4.2.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
